language: ruby
before_install:
  - sudo add-apt-repository -y ppa:miurahr/vagrant
  - sudo apt-get update -qq
  - sudo apt-get install -qq libvirt-dev libvirt-bin qemu-kvm qemu
  - sudo usermod -G kvm,libvirtd $USER
  - gem install --version '~> 1.5.2' bundler
rvm:
  - 1.9.3
  - 2.0.0
script: "bundle exec rspec spec/vagrant-kvm/"
